// Code generated by gofi generate; DO NOT EDIT.

package codegen

import (
	"net/http"
	"encoding/json"
	"io"
	"github.com/michaelolof/gofi"
	"strconv"
	"errors"
	"fmt"
)

func init() {
	gofi.RegisterCompiledSchema("HeaderQueryPathSchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_HeaderQueryPathSchema,
		ValidateResponse: gofi_validateResponse_HeaderQueryPathSchema,
	})
	gofi.RegisterCompiledSchema("CookieSchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_CookieSchema,
		ValidateResponse: gofi_validateResponse_CookieSchema,
	})
	gofi.RegisterCompiledSchema("JSONBodySchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_JSONBodySchema,
		ValidateResponse: gofi_validateResponse_JSONBodySchema,
	})
	gofi.RegisterCompiledSchema("ResponseHeaderSchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_ResponseHeaderSchema,
		ValidateResponse: gofi_validateResponse_ResponseHeaderSchema,
	})
	gofi.RegisterCompiledSchema("CustomSpecSchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_CustomSpecSchema,
		ValidateResponse: gofi_validateResponse_CustomSpecSchema,
	})
	gofi.RegisterCompiledSchema("InlineValidationsSchema", gofi.CompiledSchemaFuncs{
		ValidateRequest:  gofi_validateRequest_InlineValidationsSchema,
		ValidateResponse: gofi_validateResponse_InlineValidationsSchema,
	})
}

func gofi_validateRequest_HeaderQueryPathSchema(c gofi.BuildContext) (any, error) {
	req := &HeaderQueryPathSchema{}
	var errs []error

	// --- Headers ---
	raw_header_authorization := c.Request().Header.Get("Authorization")
	if raw_header_authorization == "" {
		errs = append(errs, errors.New("[header] Authorization: field is required"))
	}
	req.Request.Header.Authorization = raw_header_authorization
	raw_header_x_request_id := c.Request().Header.Get("X-Request-Id")
	if raw_header_x_request_id == "" {
		raw_header_x_request_id = "auto-generated"
	}
	req.Request.Header.XRequestID = raw_header_x_request_id

	// --- Query parameters ---
	raw_query_page := c.Request().URL.Query().Get("page")
	if raw_query_page == "" {
		raw_query_page = "1"
	}
	var raw_query_page_parsed int
	if raw_query_page != "" {
		if _v, _err := strconv.ParseInt(raw_query_page, 10, 64); _err == nil {
			raw_query_page_parsed = int(_v)
		} else {
			errs = append(errs, fmt.Errorf("[query] page: invalid integer: %w", _err))
		}
	}
	req.Request.Query.Page = raw_query_page_parsed
	raw_query_sort := c.Request().URL.Query().Get("sort")
	req.Request.Query.Sort = raw_query_sort
	raw_query_active := c.Request().URL.Query().Get("active")
	var raw_query_active_parsed bool
	if raw_query_active != "" {
		raw_query_active_parsed = raw_query_active == "true" || raw_query_active == "1" || raw_query_active == "yes"
	}
	req.Request.Query.Active = raw_query_active_parsed

	// --- Path parameters ---
	raw_path_id := c.Request().PathValue("id")
	if raw_path_id == "" {
		errs = append(errs, errors.New("[path] id: field is required"))
	}
	var raw_path_id_parsed int
	if raw_path_id != "" {
		if _v, _err := strconv.ParseInt(raw_path_id, 10, 64); _err == nil {
			raw_path_id_parsed = int(_v)
		} else {
			errs = append(errs, fmt.Errorf("[path] id: invalid integer: %w", _err))
		}
	}
	req.Request.Path.ID = raw_path_id_parsed
	raw_path_category := c.Request().PathValue("category")
	if raw_path_category == "" {
		errs = append(errs, errors.New("[path] category: field is required"))
	}
	req.Request.Path.Category = raw_path_category
	raw_path_rating := c.Request().PathValue("rating")
	var raw_path_rating_parsed float64
	if raw_path_rating != "" {
		if _v, _err := strconv.ParseFloat(raw_path_rating, 64); _err == nil {
			raw_path_rating_parsed = float64(_v)
		} else {
			errs = append(errs, fmt.Errorf("[path] rating: invalid float: %w", _err))
		}
	}
	req.Request.Path.Rating = raw_path_rating_parsed

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_HeaderQueryPathSchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	return gofi.ResponseResult{Body: rv.Body}, nil
}

func gofi_validateRequest_CookieSchema(c gofi.BuildContext) (any, error) {
	req := &CookieSchema{}
	var errs []error

	// --- Cookies ---
	cookie_session_id, _ := c.Request().Cookie("session_id")
	var raw_cookie_session_id string
	if cookie_session_id != nil {
		raw_cookie_session_id = cookie_session_id.Value
	}
	if raw_cookie_session_id == "" {
		errs = append(errs, errors.New("[cookie] session_id: field is required"))
	}
	req.Request.Cookie.SessionID = raw_cookie_session_id
	cookie_tracking, _ := c.Request().Cookie("tracking")
	if cookie_tracking != nil {
		req.Request.Cookie.Tracking = *cookie_tracking
	}

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_CookieSchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	for _, ck := range rv.Cookies {
		http.SetCookie(c.Writer(), &ck)
	}

	return gofi.ResponseResult{Body: rv.Body}, nil
}

func gofi_validateRequest_JSONBodySchema(c gofi.BuildContext) (any, error) {
	req := &JSONBodySchema{}
	var errs []error

	// --- Body ---
	bodyBytes, _readErr := io.ReadAll(c.Request().Body)
	if _readErr != nil {
		errs = append(errs, fmt.Errorf("[body]: failed to read body: %w", _readErr))
	} else if len(bodyBytes) == 0 {
		errs = append(errs, errors.New("[body]: request body is required"))
	} else {
		if _err := json.Unmarshal(bodyBytes, &req.Request.Body); _err != nil {
			errs = append(errs, fmt.Errorf("[body]: failed to parse JSON: %w", _err))
		} else {
			if req.Request.Body.Name == "" {
				errs = append(errs, errors.New("[body] name: field is required"))
			}
			if req.Request.Body.Email == "" {
				errs = append(errs, errors.New("[body] email: field is required"))
			}
			if req.Request.Body.Age < 1 {
				errs = append(errs, fmt.Errorf("[body] age: value must be at least 1"))
			}
			if req.Request.Body.Age > 150 {
				errs = append(errs, fmt.Errorf("[body] age: value must be at most 150"))
			}
		}
	}

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_JSONBodySchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	return gofi.ResponseResult{Body: rv.Body}, nil
}

func gofi_validateRequest_ResponseHeaderSchema(c gofi.BuildContext) (any, error) {
	req := &ResponseHeaderSchema{}
	var errs []error

	// --- Path parameters ---
	raw_path_id := c.Request().PathValue("id")
	if raw_path_id == "" {
		errs = append(errs, errors.New("[path] id: field is required"))
	}
	var raw_path_id_parsed int
	if raw_path_id != "" {
		if _v, _err := strconv.ParseInt(raw_path_id, 10, 64); _err == nil {
			raw_path_id_parsed = int(_v)
		} else {
			errs = append(errs, fmt.Errorf("[path] id: invalid integer: %w", _err))
		}
	}
	req.Request.Path.ID = raw_path_id_parsed

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_ResponseHeaderSchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	if rv.Header != nil {
		for k, v := range rv.Header {
			c.Writer().Header().Set(k, fmt.Sprint(v))
		}
	}

	return gofi.ResponseResult{Body: rv.Body}, nil
}

func gofi_validateRequest_CustomSpecSchema(c gofi.BuildContext) (any, error) {
	req := &CustomSpecSchema{}
	var errs []error

	// --- Query parameters ---
	raw_query_amount := c.Request().URL.Query().Get("amount")
	if raw_query_amount == "" {
		errs = append(errs, errors.New("[query] amount: field is required"))
	}
	var raw_query_amount_parsed int
	if raw_query_amount != "" {
		if spec, ok := c.CustomSpecs().Find("currency"); ok {
			if decoded, err := spec.Decode(raw_query_amount); err == nil {
				if casted, ok := decoded.(int); ok {
					raw_query_amount_parsed = casted
				} else {
					errs = append(errs, fmt.Errorf("[query] amount: spec returned unexpected type"))
				}
			} else {
				errs = append(errs, fmt.Errorf("[query] amount: typeCast: %w", err))
			}
		} else {
			if _v, _err := strconv.ParseInt(raw_query_amount, 10, 64); _err == nil {
				raw_query_amount_parsed = int(_v)
			} else {
				errs = append(errs, fmt.Errorf("[query] amount: invalid integer: %w", _err))
			}
		}
	}
	req.Request.Query.Amount = raw_query_amount_parsed

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_CustomSpecSchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	if rv.Header != nil {
		for k, v := range rv.Header {
			var strVal string
			switch k {
			case "X-Price":
				if spec, ok := c.CustomSpecs().Find("currency"); ok {
					if e, err := spec.Encode(v); err == nil {
						strVal = e
					} else {
						strVal = fmt.Sprint(v)
					}
				} else {
					strVal = fmt.Sprint(v)
				}
			default:
				strVal = fmt.Sprint(v)
			}
			c.Writer().Header().Set(k, strVal)
		}
	}

	return gofi.ResponseResult{Body: rv.Body}, nil
}

func gofi_validateRequest_InlineValidationsSchema(c gofi.BuildContext) (any, error) {
	req := &InlineValidationsSchema{}
	var errs []error

	// --- Query parameters ---
	raw_query_code := c.Request().URL.Query().Get("code")
	if raw_query_code == "" {
		errs = append(errs, errors.New("[query] code: field is required"))
	}
	if len(raw_query_code) < 4 {
		errs = append(errs, fmt.Errorf("[query] code: length must be at least 4"))
	}
	if len(raw_query_code) > 8 {
		errs = append(errs, fmt.Errorf("[query] code: length must be at most 8"))
	}
	req.Request.Query.Code = raw_query_code
	raw_query_age := c.Request().URL.Query().Get("age")
	var raw_query_age_parsed int
	if raw_query_age != "" {
		if _v, _err := strconv.ParseInt(raw_query_age, 10, 64); _err == nil {
			raw_query_age_parsed = int(_v)
		} else {
			errs = append(errs, fmt.Errorf("[query] age: invalid integer: %w", _err))
		}
	}
	if raw_query_age_parsed < 18 {
		errs = append(errs, fmt.Errorf("[query] age: value must be at least 18"))
	}
	if raw_query_age_parsed > 65 {
		errs = append(errs, fmt.Errorf("[query] age: value must be at most 65"))
	}
	req.Request.Query.Age = raw_query_age_parsed

	if len(errs) > 0 {
		return nil, errors.Join(errs...)
	}
	return req, nil
}

func gofi_validateResponse_InlineValidationsSchema(c gofi.BuildContext, code int, obj any) (gofi.ResponseResult, error) {
	rv := gofi.ExtractResponseFields(obj)

	return gofi.ResponseResult{Body: rv.Body}, nil
}

