package main

import (
	"bufio"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"regexp"
	"runtime"
	"strconv"
	"strings"
)

type BenchResult struct {
	Name        string
	NsPerOp     float64
	BytesPerOp  int
	AllocsPerOp int
}

type MemResult struct {
	Section string
	Router  string
	Bytes   int
}

type ParsedData struct {
	Benches  []BenchResult
	Mems     []MemResult
	Sections map[string]int
}

type AvgResult struct {
	NsPerOp     float64
	BytesPerOp  float64
	AllocsPerOp float64
}

// All router identifiers used in benchmark function names
var routers = []struct {
	prefix  string // prefix in Benchmark function name (e.g. "GofiS")
	display string // display name in the report
}{
	{"Gofi", "Gofi"},
	{"GofiS", "Gofi + Schema"},
	{"Chi", "Chi"},
	{"ChiS", "Chi + Schema"},
	{"Echo", "Echo"},
	{"EchoS", "Echo + Schema"},
}

var benchRe = regexp.MustCompile(`^(Benchmark\w+)-\d+\s+(\d+)\s+([\d.]+)\s+ns/op\s+(\d+)\s+B/op\s+(\d+)\s+allocs/op`)
var memRe = regexp.MustCompile(`^(\w+):\s+(\d+)\s+Bytes`)
var sectionRe = regexp.MustCompile(`^#(\w+)\s+Routes:\s+(\d+)`)

func parse(r io.Reader) ParsedData {
	scanner := bufio.NewScanner(r)
	data := ParsedData{Sections: map[string]int{}}
	section := ""
	for scanner.Scan() {
		line := scanner.Text()
		if m := sectionRe.FindStringSubmatch(line); m != nil {
			section = m[1]
			n, _ := strconv.Atoi(m[2])
			data.Sections[section] = n
		} else if m := memRe.FindStringSubmatch(line); m != nil {
			n, _ := strconv.Atoi(m[2])
			data.Mems = append(data.Mems, MemResult{Section: section, Router: m[1], Bytes: n})
		} else if m := benchRe.FindStringSubmatch(line); m != nil {
			ns, _ := strconv.ParseFloat(m[3], 64)
			bop, _ := strconv.Atoi(m[4])
			aop, _ := strconv.Atoi(m[5])
			data.Benches = append(data.Benches, BenchResult{Name: m[1], NsPerOp: ns, BytesPerOp: bop, AllocsPerOp: aop})
		}
	}
	return data
}

func average(benches []BenchResult) map[string]AvgResult {
	groups := map[string][]BenchResult{}
	for _, b := range benches {
		groups[b.Name] = append(groups[b.Name], b)
	}
	avgs := map[string]AvgResult{}
	for name, runs := range groups {
		var ns, by, al float64
		for _, r := range runs {
			ns += r.NsPerOp
			by += float64(r.BytesPerOp)
			al += float64(r.AllocsPerOp)
		}
		n := float64(len(runs))
		avgs[name] = AvgResult{math.Round(ns / n), math.Round(by / n), math.Round(al / n)}
	}
	return avgs
}

func fmtNs(ns float64) string {
	if ns == 0 {
		return "—"
	}
	return fmtNum(ns)
}

func fmtNum(n float64) string {
	s := fmt.Sprintf("%.0f", n)
	if len(s) <= 3 {
		return s
	}
	parts := []string{}
	for i := len(s); i > 0; i -= 3 {
		start := i - 3
		if start < 0 {
			start = 0
		}
		parts = append([]string{s[start:i]}, parts...)
	}
	return strings.Join(parts, ",")
}

func fmtBytes(b int) string {
	if b >= 1024*1024 {
		return fmt.Sprintf("%.1f MB", float64(b)/(1024*1024))
	}
	if b >= 1024 {
		return fmt.Sprintf("%d KB", b/1024)
	}
	return fmt.Sprintf("%d B", b)
}

func pickWinner(entries ...struct {
	n string
	v float64
}) string {
	var best struct {
		n string
		v float64
	}
	for _, e := range entries {
		if e.v <= 0 {
			continue
		}
		if best.v <= 0 || e.v < best.v {
			best = e
		}
	}
	if best.v <= 0 {
		return "—"
	}
	ties := 0
	for _, e := range entries {
		if e.v > 0 && e.v <= best.v*1.1 {
			ties++
		}
	}
	if ties > 1 {
		return "Tie"
	}
	return best.n
}

// benchKey builds the benchmark function name, e.g. "BenchmarkGofi_Static"
func benchKey(routerPrefix, suffix string) string {
	return "Benchmark" + routerPrefix + "_" + suffix
}

func writeResults(w io.Writer, data ParsedData) {
	avgs := average(data.Benches)
	p := func(f string, a ...any) { fmt.Fprintf(w, f+"\n", a...) }

	p("# Benchmark Results")
	p("")
	p("> Auto-generated by `go run ./cmd/report/`")
	p("")
	p("```")
	p("goos: %s", runtime.GOOS)
	p("goarch: %s", runtime.GOARCH)
	p("go: %s", runtime.Version())
	p("runs: 3")
	p("```")
	p("")

	// --- Memory ---
	p("## Memory Consumption")
	p("")
	p("| API | Routes | Gofi | Gofi + Schema | Chi | Echo |")
	p("|---|---|---|---|---|---|")
	for _, sec := range []struct{ l, k string }{{"Static", "Static"}, {"GitHub", "GithubAPI"}, {"Google+", "GPlusAPI"}, {"Parse.com", "ParseAPI"}} {
		cnt := data.Sections[sec.k]
		m := map[string]int{}
		for _, mem := range data.Mems {
			if mem.Section == sec.k {
				m[mem.Router] = mem.Bytes
			}
		}
		if len(m) == 0 {
			continue
		}
		p("| %s | %d | %s | %s | %s | %s |", sec.l, cnt, fmtBytes(m["Gofi"]), fmtBytes(m["GofiS"]), fmtBytes(m["Chi"]), fmtBytes(m["Echo"]))
	}
	p("")

	// --- Summary Table ---
	type benchRow struct {
		label  string
		suffix string
		// which router prefixes have this benchmark (empty = all base routers)
		only []string
	}

	allBase := []string{"Gofi", "GofiS", "Chi", "ChiS", "Echo", "EchoS"}
	noSchema := []string{"Gofi", "Chi", "Echo"}

	rows := []benchRow{
		{"Static Route", "Static", allBase},
		{"Single Param", "Param", allBase},
		{"5 Params", "Param5", allBase},
		{"20 Params", "Param20", []string{"Gofi", "Chi", "Echo"}},
		{"Param Write", "ParamWrite", allBase},
		{"Multi Param (2)", "MultiParam", allBase},
		{"Wildcard", "Wildcard", noSchema},
		{"Deep Nesting", "Deep", noSchema},
		{"404 Handling", "404", noSchema},
		{"Middleware ×5", "Middleware5", noSchema},
		{"Middleware ×10", "Middleware10", noSchema},
		{"Middleware ×20", "Middleware20", noSchema},
		{"JSON Bind", "BindJSON_Small", []string{"Gofi", "GofiS", "Chi", "ChiS", "Echo", "EchoS"}},
		{"JSON Response", "JSONResponse_Large", noSchema},
		{"Parallel", "Parallel", noSchema},
		{"Route Groups", "RouteGroup", noSchema},
	}

	// Add API benchmarks
	for _, api := range []struct{ label, suffix string }{
		{"Static (all)", "StaticAll"},
		{"GitHub (static)", "GithubStatic"}, {"GitHub (param)", "GithubParam"}, {"GitHub (all)", "GithubAll"},
		{"GPlus (static)", "GPlusStatic"}, {"GPlus (param)", "GPlusParam"}, {"GPlus (2 params)", "GPlus2Params"}, {"GPlus (all)", "GPlusAll"},
		{"Parse (static)", "ParseStatic"}, {"Parse (param)", "ParseParam"}, {"Parse (2 params)", "Parse2Params"}, {"Parse (all)", "ParseAll"},
	} {
		rows = append(rows, benchRow{api.label, api.suffix, allBase})
	}

	p("## Summary")
	p("")
	p("| Category | Gofi | Gofi + Schema | Chi | Chi + Schema | Echo | Echo + Schema | Winner |")
	p("|---|---|---|---|---|---|---|---|")

	for _, row := range rows {
		vals := make([]string, 6)
		var candidates []struct {
			n string
			v float64
		}

		for i, rt := range routers {
			found := false
			for _, o := range row.only {
				if o == rt.prefix {
					found = true
					break
				}
			}
			if !found {
				vals[i] = "—"
				continue
			}
			r := avgs[benchKey(rt.prefix, row.suffix)]
			vals[i] = fmtNs(r.NsPerOp)
			if r.NsPerOp > 0 {
				candidates = append(candidates, struct {
					n string
					v float64
				}{rt.display, r.NsPerOp})
			}
		}
		win := pickWinner(candidates...)
		p("| %s | %s | %s | %s | %s | %s | %s | %s |",
			row.label, vals[0], vals[1], vals[2], vals[3], vals[4], vals[5], win)
	}
	p("")

	// --- Detailed micro tables ---
	p("## Detailed Results")
	p("")

	microTests := []struct {
		title, suffix string
		prefixes      []string
	}{
		{"Static Route `GET /`", "Static", allBase},
		{"Single Param `GET /user/:name`", "Param", allBase},
		{"5 Params `GET /:a/:b/:c/:d/:e`", "Param5", allBase},
		{"20 Params `GET /:a/:b/.../:t`", "Param20", noSchema},
		{"Param Write `GET /user/:name`", "ParamWrite", allBase},
		{"Multi Param `GET /users/:id/posts/:id`", "MultiParam", allBase},
		{"Wildcard `GET /files/*`", "Wildcard", noSchema},
		{"Deep Nesting", "Deep", noSchema},
		{"404 Handling", "404", noSchema},
	}

	p("### Micro Benchmarks")
	p("")
	for _, t := range microTests {
		p("#### %s", t.title)
		p("")
		p("| Router | ns/op | B/op | allocs/op |")
		p("|---|---|---|---|")
		for _, rt := range routers {
			found := false
			for _, o := range t.prefixes {
				if o == rt.prefix {
					found = true
					break
				}
			}
			if !found {
				continue
			}
			if g := avgs[benchKey(rt.prefix, t.suffix)]; g.NsPerOp > 0 {
				p("| %s | %s | %.0f | %.0f |", rt.display, fmtNum(g.NsPerOp), g.BytesPerOp, g.AllocsPerOp)
			}
		}
		p("")
	}

	// Middleware
	p("### Middleware Scalability")
	p("")
	p("| Middlewares | Gofi | Chi | Echo | Gofi allocs | Chi allocs | Echo allocs |")
	p("|---|---|---|---|---|---|---|")
	for _, c := range []string{"5", "10", "20"} {
		g := avgs[benchKey("Gofi", "Middleware"+c)]
		ch := avgs[benchKey("Chi", "Middleware"+c)]
		ec := avgs[benchKey("Echo", "Middleware"+c)]
		p("| %s | %s | %s | %s | %.0f | %.0f | %.0f |", c, fmtNum(g.NsPerOp), fmtNum(ch.NsPerOp), fmtNum(ec.NsPerOp), g.AllocsPerOp, ch.AllocsPerOp, ec.AllocsPerOp)
	}
	p("")

	// JSON
	p("### Data Handling")
	p("")
	p("#### JSON Binding (Small Payload)")
	p("")
	p("| Router | ns/op | B/op | allocs/op |")
	p("|---|---|---|---|")
	for _, rt := range routers {
		if g := avgs[benchKey(rt.prefix, "BindJSON_Small")]; g.NsPerOp > 0 {
			p("| %s | %s | %.0f | %.0f |", rt.display, fmtNum(g.NsPerOp), g.BytesPerOp, g.AllocsPerOp)
		}
	}
	p("")
	p("#### JSON Response (100 items)")
	p("")
	p("| Router | ns/op | B/op | allocs/op |")
	p("|---|---|---|---|")
	for _, pref := range []string{"Gofi", "Chi", "Echo"} {
		if g := avgs[benchKey(pref, "JSONResponse_Large")]; g.NsPerOp > 0 {
			p("| %s | %s | %.0f | %.0f |", pref, fmtNum(g.NsPerOp), g.BytesPerOp, g.AllocsPerOp)
		}
	}
	p("")

	// Concurrency + Route Groups
	for _, sec := range []struct{ title, suffix string }{{"Concurrency", "Parallel"}, {"Route Groups", "RouteGroup"}} {
		p("### %s", sec.title)
		p("")
		p("| Router | ns/op | B/op | allocs/op |")
		p("|---|---|---|---|")
		for _, pref := range []string{"Gofi", "Chi", "Echo"} {
			if g := avgs[benchKey(pref, sec.suffix)]; g.NsPerOp > 0 {
				p("| %s | %s | %.0f | %.0f |", pref, fmtNum(g.NsPerOp), g.BytesPerOp, g.AllocsPerOp)
			}
		}
		p("")
	}

	// Real-world APIs
	apiSections := []struct {
		title string
		mem   string
		tests []struct{ l, s string }
	}{
		{"GitHub API", "GithubAPI", []struct{ l, s string }{{"Static", "GithubStatic"}, {"Param", "GithubParam"}, {"All", "GithubAll"}}},
		{"Google+ API", "GPlusAPI", []struct{ l, s string }{{"Static", "GPlusStatic"}, {"1 Param", "GPlusParam"}, {"2 Params", "GPlus2Params"}, {"All", "GPlusAll"}}},
		{"Parse.com API", "ParseAPI", []struct{ l, s string }{{"Static", "ParseStatic"}, {"1 Param", "ParseParam"}, {"2 Params", "Parse2Params"}, {"All", "ParseAll"}}},
	}

	for _, api := range apiSections {
		cnt := data.Sections[api.mem]
		p("### %s (%d routes)", api.title, cnt)
		p("")
		p("| Benchmark | Gofi | Gofi + Schema | Chi | Echo | Echo + Schema |")
		p("|---|---|---|---|---|---|")

		// Memory
		m := map[string]int{}
		for _, mem := range data.Mems {
			if mem.Section == api.mem {
				m[mem.Router] = mem.Bytes
			}
		}
		if len(m) > 0 {
			p("| Memory | %s | %s | %s | %s | %s |", fmtBytes(m["Gofi"]), fmtBytes(m["GofiS"]), fmtBytes(m["Chi"]), fmtBytes(m["Echo"]), fmtBytes(m["EchoS"]))
		}

		for _, t := range api.tests {
			g := avgs[benchKey("Gofi", t.s)]
			gs := avgs[benchKey("GofiS", t.s)]
			c := avgs[benchKey("Chi", t.s)]
			e := avgs[benchKey("Echo", t.s)]
			es := avgs[benchKey("EchoS", t.s)]
			p("| %s (ns/op) | %s | %s | %s | %s | %s |", t.l, fmtNs(g.NsPerOp), fmtNs(gs.NsPerOp), fmtNs(c.NsPerOp), fmtNs(e.NsPerOp), fmtNs(es.NsPerOp))
			if t.l == "All" {
				p("| %s (B/op) | %.0f | %.0f | %.0f | %.0f | %.0f |", t.l, g.BytesPerOp, gs.BytesPerOp, c.BytesPerOp, e.BytesPerOp, es.BytesPerOp)
				p("| %s (allocs) | %.0f | %.0f | %.0f | %.0f | %.0f |", t.l, g.AllocsPerOp, gs.AllocsPerOp, c.AllocsPerOp, e.AllocsPerOp, es.AllocsPerOp)
			}
		}
		p("")
	}

	// Schema overhead comparison
	p("### Schema Overhead")
	p("")
	p("| Scenario | Gofi | Gofi + Schema | Chi | Chi + Schema | Echo | Echo + Schema |")
	p("|---|---|---|---|---|---|---|")
	for _, item := range []struct{ l, s string }{{"Static", "Static"}, {"1 param", "Param"}, {"5 params", "Param5"}, {"JSON bind", "BindJSON_Small"}} {
		vals := make([]string, 6)
		for i, rt := range routers {
			if g := avgs[benchKey(rt.prefix, item.s)]; g.NsPerOp > 0 {
				vals[i] = fmtNum(g.NsPerOp)
			} else {
				vals[i] = "—"
			}
		}
		p("| %s | %s | %s | %s | %s | %s | %s |", item.l, vals[0], vals[1], vals[2], vals[3], vals[4], vals[5])
	}
	p("")
}

func main() {
	fmt.Println("🚀 Running benchmarks... (this may take 10-15 minutes)")
	fmt.Println()

	cmd := exec.Command("go", "test", "-bench=.", "-benchmem", "-count=3", "-timeout=20m")
	cmd.Dir = findBenchDir()
	cmd.Stderr = os.Stderr

	output, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Benchmark failed: %v\n", err)
		os.Exit(1)
	}

	data := parse(strings.NewReader(string(output)))
	avgs := average(data.Benches)

	fmt.Printf("📊 Parsed %d unique benchmarks from %d total runs\n", len(avgs), len(data.Benches))
	fmt.Printf("💾 Parsed %d memory measurements\n", len(data.Mems))
	fmt.Println()

	resultsPath := findBenchDir() + "/benchmark-results.md"
	f, err := os.Create(resultsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create benchmark-results.md: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	writeResults(f, data)
	fmt.Printf("✅ Results written to %s\n", resultsPath)
}

func findBenchDir() string {
	if _, err := os.Stat("bench_test.go"); err == nil {
		return "."
	}
	if _, err := os.Stat("../bench_test.go"); err == nil {
		return ".."
	}
	fmt.Fprintln(os.Stderr, "Error: cannot find bench_test.go. Run from the gofi-benchmarks directory.")
	os.Exit(1)
	return ""
}
